### ISSUE TITLE
Add LLBLGen to ORM Cookbook

### ISSUE THREAD

**Issue by Grauenwolf** [Grauenwolf/DotNet-ORM-Cookbook#10]
We're restarting the ORM Cookbook project with an emphasis on .NET Core. If you are interested in participating we would love to have LLBLGen in the new cookbook.

If you're not, feel free to close this ticket.

**Comment by FransBouma** [comment]
I'll have a look in the coming 2 weeks :)

**Comment by FransBouma** [comment]
I have a hard time to get started. How do I create the SQL Server database? I know how to create a database, but I recon you want to have it at '.' using the scripts that are provided, but I don't know how to use these as my local SQL Server is a named instance. 

**any** documentation about this is helpful, as currently there's zip.

**Comment by FransBouma** [comment]
Turned out the connection string is the only thing. So for the rest I think everything works. See PR #61

**Comment by Grauenwolf** [comment]
A single dot is just the abbreviation for `localhost`. But I do agree that we need more contributor documentation.

**Comment by FransBouma** [comment]
Yeah I thought that was it, but it might be better to use localdb perhaps? (and ship the DB with the repo?) otherwise users with a named instance can't run the tests. :)

**Comment by Grauenwolf** [comment]
I don't have any experience with localdb, but I like the idea of it.

I'll add it to the list.
