### ISSUE TITLE
Implement Simple Stored Procedures for LLBLGen Pro

### ISSUE THREAD

**Issue by Grauenwolf** [Grauenwolf/DotNet-ORM-Cookbook#124]
See #27

**Comment by FransBouma** [comment]
The stored procedure `HR.CreateEmployeeClassification` doesn't seem correct to me. It obtains the inserted PK, but ... assigns it to a local parameter. Why isn't it assigned to an out parameter? It's returned as a resultset, but that's kind of cheating here IMHO. I'd opt for having the key returned as an output parameter like it's usually done (at least, this is the first time I see it done this way).

**Comment by Grauenwolf** [comment]
It was a common pattern in many places where I've worked in the past. They liked it because they could just call `ExecuteScalar()` when using raw ADO.

But yes, I do intend to include an output parameter in the future (#119 and #120).

**Comment by FransBouma** [comment]
Ok ;) 

Not an oracle shop, I recon :P

**Comment by Grauenwolf** [comment]
Nope. For better or worse, I've been doing mostly SQL Server for the last 20 years.
