### ISSUE TITLE
Implement Pagination for RepoDb

### ISSUE THREAD

**Issue by Grauenwolf** [Grauenwolf/DotNet-ORM-Cookbook#142]
See #33

**Comment by mikependon** [comment]
The pagination concept of RepoDb is Paging not (Skip/Take).

- Let us say page 2 for take 10, then I will take the 20th to 30th rows.
- Let us say page 0 for take 10, then I will take the 1st to 10th row.

Seems, I need to make a raw-SQL calls  for this.

**Comment by Grauenwolf** [comment]
For the skip/take example, just use this formula:

    Page = skip / take
    PageSize = take

The only once that's tricky is the "key set" or  "skip past" example.

**Comment by mikependon** [comment]
This has already been asked towards me inside the organization :) . That formula will not work in most cases as you can skip the rows that is not modular to RowsPerPage. But I will try to play around with it and try to see if I can make it on this Cookbook. Or maybe, I will introduce a SkipQuery (working differently from BatchQuery).

**Comment by Grauenwolf** [comment]
For the purpose of the cookbook the formula is valid. I don't think it's necessary for us to demonstrate skipping an arbitrary number of rows.

**Comment by mikependon** [comment]
Great! :) I will do that then :)
