### ISSUE TITLE
Please document the db changes

### ISSUE THREAD

**Issue by FransBouma** [Grauenwolf/DotNet-ORM-Cookbook#169]
I'm sorry, but the DB changes are really obscure to find. Now I have to update the database and add fields to the Division table. I decided to drop that table and recreate it. Inserting the data won't work as it depends on employee which violates an FK etc. 

Also 1 big script which basically creates all tables and inserts all rows might be preferable than all the separate sql files of which are part of a DB project I think which I have no idea what to do with :) 

(e.g. I don't know the order in which these have to be applied. I can generate a DDL SQL script for the tables if you want, in the right order)

This will go away IF we move to a localdb instance I think.

**Comment by Grauenwolf** [comment]
That can be arranged. 

When I publish the database it generates a unified script anyways. So moving forward I can just check that in.

I'll also be careful to call out database changes in the future in tickets.

**Comment by FransBouma** [comment]
thanks! A create script that simple creates a new fresh db would be ideal :)
