### ISSUE TITLE
Use Case: Model with Child Records

### ISSUE THREAD

**Issue by Grauenwolf** [Grauenwolf/DotNet-ORM-Cookbook#17]
Scenario 1:

1. Create a `ProductLine` 
2. Add several `Product` rows to that `ProductLine`
3. Return them on one call

Scenario 2:

1. Create a `ProductLine` and its `Product` rows at the same time
2. Return them on one call

- [x] Test cases
- [x] ADO
- [x] Chain
- [x] Dapper
- [x] EF Core
- [ ] NHibernate
- [x] RepoDB
- [x] ServiceStack
- [x] Documentation 
- [x] LLBL Gen Pro

**Comment by Grauenwolf** [comment]
New tickets created for remaining implementations.

**Comment by FransBouma** [comment]
The definition of IProductLine<T> is odd, why is it generic? Why not have IProductLine, and 
as implementation:

```
    public interface IProductLine
    {
        public int ProductLineKey { get; set; }

        string? ProductLineName { get; set; }

        ICollection<IProduct> Products { get; }
    }
```

**Comment by FransBouma** [comment]
The repository is also inconsistent with ModelWithLookup. There I had to limit the work on related entities, and with *this* repository I have to take into account the work on related entities. Like, 'Delete', does that have to delete the related entities as well? Or not? Looking at the ModelWithLookup repo, one would think "no", but it has to delete the related entities if you look at the tests in the core repo.

**Comment by FransBouma** [comment]
The description of the ticket here is straightforward, but the repository has to implement more. E.g. the thing I'm a bit struggling with is the Update(ProductLine) method (it's understandable, but really what's the purpose?)

LLBLGen Pro has a feature where I can track which entities have been removed from a collection, in memory. So I don't have to fetch them from the DB again and then do a dance which one is kept etc. However I have to inject this tracker into the collection before the collection is modified of course. 

So for now I'll add the tracker to the repository's create method needed to pass the test, but it's not needed for other scenarios, hence the lame part.

**Comment by Grauenwolf** [comment]
> The repository is also inconsistent with ModelWithLookup. There I had to limit the work on related entities, and with this repository I have to take into account the work on related entities.

Yep, that's the intention. I want to offer both options to the developer.

> LLBLGen Pro has a feature where I can track which entities have been removed from a collection, in memory. So I don't have to fetch them from the DB again and then do a dance which one is kept etc. 

I haven't figured out how to structure it yet, but we need a better distinction between these two scenarios:

* These objects are in memory all the time
* These objects went to the browser and came back again, so any internal tracking information is lost. 

Both are important, as they represent different opportunities and restrictions.

**Comment by FransBouma** [comment]
> Yep, that's the intention. I want to offer both options to the developer.

Ok, perhaps it should be a bit more clear from the repo to implement (e.g. as a comment on the interface method perhaps?) that e.g. the entity passed in should be saved and all related entities as well, *or* that only the entity passed in should be saved.

> Both are important, as they represent different opportunities and restrictions.

Agreed. I've implemented both, perhaps a different test + update method to reflect these 2 scenarios?

**Comment by Grauenwolf** [comment]
> that e.g. the entity passed in should be saved and all related entities as well, or that only the entity passed in should be saved.

I think I can rewrite the test to have 

* Update
* UpdateGraph
* UpdateGraphWithDeletes(productLine)
* UpdateGraphWithDeletes(prroductLine, ProductKeysToRemove)

I'll send you a PR after I've given it more thought.

**Comment by Grauenwolf** [comment]
> perhaps a different test + update method to reflect these 2 scenarios?

Yes, it would have to be a different test case. 

And in the interest of fairness, for the "in memory" scenario the NHibernate fans have been asking me to keep the ISesson active. Which of course will muddy the test harness, so this change might get delayed.

**Comment by Grauenwolf** [comment]
@FransBouma 

What do you think about this change to `IModelWithChildrenRepository`?

https://github.com/Grauenwolf/DotNet-ORM-Cookbook/commit/680d8c8c07feaf411b0e4c61112e25d5d88d8870#diff-5da89fb2ddc649e110075bc6b36f76b3
