### ISSUE TITLE
Transactions for LLBLGen Pro

### ISSUE THREAD

**Issue by Grauenwolf** [Grauenwolf/DotNet-ORM-Cookbook#176]
We got a request to include transactions in examples where appropriate. That is to say, in cases where multiple statements are being executed and the ORM doesn't provide its own transactional support.

For example, ADO and Dapper always need transactions. EF Core usually doesn't because `SaveChanges` will create a transaction automatically if one doesn't exist.

Please review the LLBLGen Pro examples and update if appropriate.

**Comment by Grauenwolf** [comment]
See also #35.

**Comment by FransBouma** [comment]
Will double check. I think I've made sure all operations are in explicit transactions if necessary (it otherwise creates transactions by itself, e.g. by saving a graph or set)

**Comment by FransBouma** [comment]
All good. Have cleaned up the code a bit so it's better readable (no long lines anymore).

**Comment by FransBouma** [comment]
(this should make the LLBLGen Pro code commit to #196 )
