### ISSUE TITLE
Transactions for RepoDb

### ISSUE THREAD

**Issue by Grauenwolf** [Grauenwolf/DotNet-ORM-Cookbook#177]
We got a request to include transactions in examples where appropriate. That is to say, in cases where multiple statements are being executed and the ORM doesn't provide its own transactional support.

For example, ADO and Dapper always need transactions. EF Core usually doesn't because `SaveChanges` will create a transaction automatically if one doesn't exist.

Please review the RepoDb examples and update if appropriate.

**Comment by Grauenwolf** [comment]
See also #35.

**Comment by mikependon** [comment]
RepoDb accepts transaction as an argument in all operations. However when it comes to batch operations, it creates a Transaction automatically. In which Scenario is this?

**Comment by Grauenwolf** [comment]
This one looks like it may need transactions. 

https://github.com/Grauenwolf/DotNet-ORM-Cookbook/blob/master/ORM%20Cookbook/Recipes.RepoDb/ModelWithChildren/ModelWithChildrenScenario.cs

For example, in the Create function, we probably want a transaction around the Insert and InsertAll lines.

**Comment by mikependon** [comment]
Okay! Then I will revisit it all :)

**Comment by mikependon** [comment]
Now, I am creating a separate scenarios for transaction like what the other's did. I did not extended the ModelWithChildrenScenario.
