### ISSUE TITLE
Review InsertWithRefresh

### ISSUE THREAD

**Issue by Grauenwolf** [Grauenwolf/DotNet-ORM-Cookbook#184]
https://github.com/Grauenwolf/DotNet-ORM-Cookbook/blob/master/ORM%20Cookbook/Recipes.RepoDb/MultipleCrud/MultipleCrudScenario.cs

**Comment by mikependon** [comment]
I actually need more enlightenment on this use case. What is really the intention why we need to insert it 1-by-1? Should it not be just passing the test? Or else, can you fail the RepoDb test so I can act on it?

Apology for this 3 question marks. :)

**Comment by Grauenwolf** [comment]
The intent is that it update the original objects with their new primary keys. 

Judging by `InsertBatchReturnKeys`, it's doing exactly what it needs to. But I might extend the tests to be 100% sure.

**Comment by Grauenwolf** [comment]
The only reason I'm looking at this is you added a todo asking me to.

**Comment by Grauenwolf** [comment]
Works as expected.

**Comment by mikependon** [comment]
Thanks! :)
