### ISSUE TITLE
Implement Dynamic Sorting for RepoDb

### ISSUE THREAD

**Issue by Grauenwolf** [Grauenwolf/DotNet-ORM-Cookbook#198]
For most of the LINQ-based ORMs, we were able to use `Recipes\DynamicSorting\DynamicSortingExtensions.cs` for converting strings into `OrderBy` calls. But this doesn't work for RepoDB because `Query` is returning an `IEnumerable` instead of an `IQueryable`.

See #92.

**Comment by mikependon** [comment]
It is supported via an OrderField object. Have to pass it before execution; the orsering execution will happen on the DB instead. Anyway, will lool at it soon.

**Comment by Grauenwolf** [comment]
Oh, I see it now. That looks easy enough. I'll do it now.

**Comment by Grauenwolf** [comment]
And done. Thank you.

**Comment by mikependon** [comment]
Thanks :)
