### ISSUE TITLE
Use Case: Multiple Databases with the Same Code

### ISSUE THREAD

**Issue by Grauenwolf** [Grauenwolf/DotNet-ORM-Cookbook#238]
Demonstrate accessing both SQL Server and PostgreSQL using the same code.

**Comment by Grauenwolf** [comment]
EF Core Example: https://github.com/avi1989/DbContextForMultipleDatabases

**Comment by FransBouma** [comment]
Is a good scenario as it's used a lot in practice. And I should be able to support this without lifting a finger too :)

**Comment by mikependon** [comment]
I liked this too :)

**Comment by Grauenwolf** [comment]
I've got the tests written, but I've got a little bit of work left to do for EF Core. But I can comment that out and just push the tests.
