### ISSUE TITLE
Use case: "Insert large number of records at one time use a bulk insert"

### ISSUE THREAD

**Issue by Grauenwolf** [Grauenwolf/DotNet-ORM-Cookbook#24]
This demonstrates basic bulk insert capabilities. 

No echo is needed, the rows are simply inserted and forgotten.

Sample sizes: 
* 100
* 1,000
* 10,000
* 100,000

Databases:
* SQL Server
* MySQL
* PostgreSQL
* (others?)

- [x] Test cases
- [x] ADO
- [ ] Chain
- [ ] Dapper
- [ ] EF Core
- [ ] NHibernate
- [ ] RepoDB
- [ ] ServiceStack
- [ ] Documentation  
- [ ] LLBL Gen Pro

**Comment by mikependon** [comment]
I have been in a discussion before, that I said *Batch* is completely different from *Bulk*, but you were on the other side of the coin.

Are we comparing a *Batch Operation* from *Bulk Operation* here? (ie: *InsertAll* vs *BulkInsert*)?

**Comment by Grauenwolf** [comment]
The use case is just "How to I insert a bunch of records all at one time?".

It's up to the individual ORMs to decide which method is perferable.

**Comment by Grauenwolf** [comment]
If you want, we can create a separate use case that specifically demonstrates batch operations or specifically demonstrates bulk operations.

**Comment by mikependon** [comment]
Yes, let us do it that way. In that sense, we are not doing a huge-gap capability comparison. For me, even in the lower level, *bulk* is really different from *batch*. :)

**Comment by Grauenwolf** [comment]
@FransBouma Does LLBLGen Pro support bulk inserts?

**Comment by Grauenwolf** [comment]
@mattjcowan , Does ServiceStack support bulk inserts?

**Comment by FransBouma** [comment]
@Grauenwolf yes, I've enabled these in set inserts in the scenarios (by setting batchsize> 0 :) )

**Comment by Grauenwolf** [comment]
By bulk insert I mean database-specific stuff like `SqlBulkCopy`. When I run the `LargeBatch` tests I'm seeing comparable performance to using ADO with SQL to batch-insert rows, not `SqlBulkCopy` speeds.

**Comment by FransBouma** [comment]
aaahhh no, I don't support bulkinsert functionality yet. Just batching of inserts into one DbCommand to avoid roundtrips. that can be significantly faster, but indeed not as fast as bulkcopy.

**Comment by Grauenwolf** [comment]
Ok, thanks.

**Comment by mattjcowan** [comment]
@Grauenwolf I think it's possible (though not necessarily officially documented). If I understand correctly, it could probably be done in the same way some of these extension methods were constructed (probably would apply to other frameworks as well), see: https://gist.github.com/zelid/6965002, https://forums.servicestack.net/t/how-to-insert-multiple-records-with-1-insert/6494/5

**Comment by Grauenwolf** [comment]
In a way I feel that's 'cheating', but the goal of this is to help people solve problems. And it certainly looks like this will solve the "I have ServiceStack and need to bulk insert data" problem.

**Comment by mattjcowan** [comment]
I know what you mean. My thought is in the case where you are able to use ORM apis to get a good snapshot of a model and it's bindings to a database (i.e.: property to column, entity to table/view/sp, FK discovery from/to, index discovery, etc...), it showcases how missing APIs can often be patched without having to resort to raw sql or alternative methods, such as in this creative case of doing bulk loads/updates. I think for ServiceStack, it embeds Dapper on purpose as part of its api to do exactly that (to offer flexibility to the dev while re-using the same DbConnectionFactory), although it's pretty rare one needs to reach for it imo. The model definitions in ServiceStack let you get enough information out of them  for example to sort types topologically based on foreign key relationships to properly create tables in the right order, and things of that sort. I know LLBLGen also has that information built-into it, at least during code generation, but I'm pretty sure also in the generated code as well. So to the extent that an ORM lets you have access to that information, it could be a differentiator, and I imagine many of the ORMs have a way to do that. As far as whether or not to put this into repo of framework/orm examples, I'm not sure. Depends on whether the repo intends to demo supported and purposeful implementations by the ORM creators, or be a tool for developers trying to quickly see how to perform a specific task with their ORM of choice.

**Comment by Grauenwolf** [comment]
> My thought is in the case where you are able to use ORM apis to get a good snapshot of a model and it's bindings to a database (i.e.: property to column, entity to table/view/sp, FK discovery from/to, index discovery, etc...), it showcases how missing APIs can often be patched without having to resort to raw sql or alternative methods, such as in this creative case of doing bulk loads/updates.

That's a very good point.

**Comment by Grauenwolf** [comment]
The mistake I made the first time I tried doing this was making it a showcase for the ORM's built-in features. No one cares about that because the documentation already does a better job of showing off the good parts.

> a tool for developers trying to quickly see how to perform a specific task with their ORM of choice.

This is where we can be a real benefit to the community. If something requires an extension or work-around to accomplish the task, we should include it. For example, there is what I'm calling [`DynamicSortingExtensions`](https://grauenwolf.github.io/DotNet-ORM-Cookbook/DynamicSorting.htm#scenario-prototype) being used by EF 6/Core, LLBLGen Pro, and LinqToDB. (I might use it for ServiceStack as well as an alternate implementation.)

In #191, I'm even going to pull in some 3rd party extensions to EF Core.

**Comment by Grauenwolf** [comment]
@mattjcowan Feel free to grab #204 if you have the time. Otherwise I'll try to get to it later in the week.

**Comment by mikependon** [comment]
I think it is okay to have the extension method be embedded as part of the cookbook as long as that extension is visible to the documentation. The most important thing is, the use-case is addressed with such implementations.

It is on the developer's perusal to assess which ORM they prefer to use to cater such scenario.

**Comment by FransBouma** [comment]
> This is where we can be a real benefit to the community. If something requires an extension or work-around to accomplish the task, we should include it. For example, there is what I'm calling [`DynamicSortingExtensions`](https://grauenwolf.github.io/DotNet-ORM-Cookbook/DynamicSorting.htm#scenario-prototype) being used by EF 6/Core, LLBLGen Pro, and LinqToDB. (I might use it for ServiceStack as well as an alternate implementation.)

LLBLGen Pro does support it, but it's not that simple, you have to use more code than the extension uses. This extension is indeed much easier. And I agree, using these kind of things is a big plus for the book :)

**Comment by Grauenwolf** [comment]
Oops, you may want to update the `DynamicSorting.md` file.

**Comment by Grauenwolf** [comment]
And since I've got all of your attention, I've been thinking about documentation. 

It would be useful if the markdown files had links to the offical documentation for specific tasks. 

For example, I did it in the Linq2Db section on bulk inserts.

https://grauenwolf.github.io/DotNet-ORM-Cookbook/BulkInsert.htm#linq-to-db

**Comment by FransBouma** [comment]
> Oops, you may want to update the `DynamicSorting.md` file.

Done :) See #205

**Comment by FransBouma** [comment]
Regarding doc links: good point :) Will see if I can add some.
