### ISSUE TITLE
Use case: ORM Populated Audit Columns

### ISSUE THREAD

**Issue by Grauenwolf** [Grauenwolf/DotNet-ORM-Cookbook#25]
In this use case the ORM must provide the following information:

1. CreatedByUserKey
2. ModifiedByUserKey
3. CreatedDateTime
4. UpdatedDateTime

- [x] Test cases
- [x] ADO
- [x] Chain
- [x] Dapper
- [x] EF Core
- [ ] NHibernate
- [ ] RepoDB
- [ ] ServiceStack
- [x] Documentation  
- [ ] LLBL Gen Pro
- [ ] LINQ to DB

****

## Database Changes

New columns for `TABLE HR.Department`

```
    CreatedDate DATETIME2(7) NULL,
    ModifiedDate DATETIME2(7) NULL,
    CreatedByEmployeeKey INT NULL
        CONSTRAINT FK_Department_CreatedByEmployeeKey
        REFERENCES HR.Employee (EmployeeKey),
    ModifiedByEmployeeKey INT NULL
        CONSTRAINT FK_Department_ModifiedByEmployeeKey
        REFERENCES HR.Employee (EmployeeKey)
```

**Comment by mikependon** [comment]
Is this something that is being set from the client application? Or, behind the scene?

**Comment by Grauenwolf** [comment]
I'm envisioning the test calling a method such as `Create( Customer newCustomer, User user)`. The business logic layer shouldn't have to know anything about the audit columns, other than to provide the `User` object.

For EF I believe you can intercept the INSERT operations in the DBConext to automatically update the audit columns, but I'd have to check.

For ADO or Dapper, the repository would explicitly update the columns.

**Comment by mikependon** [comment]
Got you. Thanks!

**Comment by Grauenwolf** [comment]
Remaining ORM-specific tickets created.

**Comment by FransBouma** [comment]
The test is flawed. You immediately run the update after the insert on the same row, and then compare datetime2 values. On my machine they're identical for insert and update and therefore it fails. I've introduced a sleep of 500ms before the update.

**Comment by Grauenwolf** [comment]
@FransBouma Thank you.
