### ISSUE TITLE
Error: Freshly pulled project could not be built

### ISSUE THREAD

**Issue by mikependon** [Grauenwolf/DotNet-ORM-Cookbook#259]
Hi Jonathan, just FYI, I just freshly pulled the ORM Cookbook project and I could not build it.

Below is the exception.

![image](https://user-images.githubusercontent.com/591015/78790224-815f5380-79ae-11ea-854c-075f3116ae50.png)

FYI: @FransBouma

**Comment by FransBouma** [comment]
Looks like a problem I should fix. Will look at it tomorrow!

**Comment by mikependon** [comment]
@FransBouma - I just fixed it awhile back. I just issued a PR. Once the PR is closed, then I will close this one as well.

**Comment by FransBouma** [comment]
thanks!

**Comment by Grauenwolf** [comment]
Done.
