### ISSUE TITLE
EF Core query filter.

### ISSUE THREAD

**Issue by Arnab-Developer** [Grauenwolf/DotNet-ORM-Cookbook#264]
I want to create an example on EF Core query filter. If you agree, I can work on that and send you a PR. Please let me know.

**Comment by Grauenwolf** [comment]
I'll allow it. 

There's no rule that you can't demonstrate a feature that's unique to a single ORM. We've just been focusing on the more general cases first.

**Comment by Arnab-Developer** [comment]
Thanks.

**Comment by Arnab-Developer** [comment]
I send a PR #265 for EF Core query filter.
