### ISSUE TITLE
Use Case: Arbitrary table read

### ISSUE THREAD

**Issue by Grauenwolf** [Grauenwolf/DotNet-ORM-Cookbook#271]
Read all of the columns from an arbitrary table. ORM chooses the return type.

**Comment by Grauenwolf** [comment]
@mikependon @lukevp @mattjcowan @Arnab-Developer 

Here is another one of those 'database discovery' kind of use cases. Again, if you think this is one that applies to your ORM go ahead and implement it.

**Comment by Arnab-Developer** [comment]
@Grauenwolf I have implemented this with EF Core and send a PR (#274).
