### ISSUE TITLE
Implement Arbitrary table read for LLBLGen Pro

### ISSUE THREAD

**Issue by Grauenwolf** [Grauenwolf/DotNet-ORM-Cookbook#285]
See #271

**Comment by FransBouma** [comment]
Is this about "Read all column meta data of table X", or about "Read all data from table X", where there's no pre-defined mapping available?

**Comment by Grauenwolf** [comment]
Read all data from table X", where there's no pre-defined mapping available.

Basically for dealing with unknown database schemas.

**Comment by FransBouma** [comment]
I have to say...

`command.CommandText = $"SELECT * FROM [{schema}].[{tableName}];";`
I have no idea why anyone would **want** to do this. 'dealing with unknown database schemas' is something that might come up in theory, but in practice, you can't do much with the returned data. Sure you can dump the datatable in some grid but that's about it. What has been gained? 

I now have to write DbCommand using code as low level as they come. I'll add big red remark under the 'LLBLGen Pro' section on that page with "Don't do this. Discover the schema and build upon that".

**Comment by FransBouma** [comment]
Implemented
