### ISSUE TITLE
Use case: Return a single value

### ISSUE THREAD

**Issue by mikependon** [Grauenwolf/DotNet-ORM-Cookbook#31]
This is equivalent to calling a DbCommand.ExecuteScalar() method.

- [x] Test cases
- [x] ADO
- [x] Chain
- [x] Dapper
- [x] EF Core
- [ ] NHibernate
- [ ] RepoDB
- [ ] ServiceStack
- [x] Documentation  
- [ ] LLBL Gen Pro

**Comment by Grauenwolf** [comment]
I'm thinking this needs to be two use cases. One for scalar values from normal queries and one from Scalar Value Functions.

**Comment by Grauenwolf** [comment]
For example, 

    SELECT Max(CreatedDate) from Employee

vs

    SELECT value FROM dbo.MyFunction( @a, @b)
    EXEC dbo.ScalarProc( @a, @b)

**Comment by Grauenwolf** [comment]
Remainin ORM tickets created.

**Comment by FransBouma** [comment]
The EF Core queries are a bit odd. 
You do:
```
return context.Division.Where(d => d.DivisionName == divisionName).SingleOrDefault()?.DivisionKey;
```
but that projects the whole entity first, then selects a field. 
why not do:
```
return context.Division.Where(d => d.DivisionName == divisionName).Select(d=>d.DivisionKey).SingleOrDefault();
```
? 
Also, this could crash if there are more divisions with the same name. I think you meant 'FirstOrDefault()' ?

**Comment by FransBouma** [comment]
Ah, I see why you did this: as FirstOrDefault() on a select of the field will always return a non-null value as the PK is a non-nullable field.

**Comment by FransBouma** [comment]
The workaround is then:
```
context..Division.Where(d => d.DivisionName == divisionName).Select(d=>d.DivisionKey as int?).FirstOrDefault();
```
:)

**Comment by Grauenwolf** [comment]
> Ah, I see why you did this: as FirstOrDefault() on a select of the field will always return a non-null value as the PK is a non-nullable field.

You give me too much credit. I simply forgot that I was supposed to do the projection before calling Single().

The code has been fixed.
