### ISSUE TITLE
Database Setup: PostgreSQL

### ISSUE THREAD

**Issue by Grauenwolf** [Grauenwolf/DotNet-ORM-Cookbook#32]
Create a project that, when run, will rebuild a PostgreSQL database.

You can steal the code from the Chain tests.

**Comment by mikependon** [comment]
Honestly, this cookbook can expand to all scenarios. But I suggest, we should limit it first to SQL Server. In anyway, it is your call.

**Comment by Grauenwolf** [comment]
There are some things that are weird in non-SQL Server databases that I want to cover.

And someone wanted to include Marten examples, which is PostgreSQL only.
