### ISSUE TITLE
Use Case: Pagination

### ISSUE THREAD

**Issue by mikependon** [Grauenwolf/DotNet-ORM-Cookbook#33]
An ORM should show how to paginate the records.

- [x] Test cases
- [x] ADO
- [x] Chain
- [x] Dapper
- [ ] EF Core
- [ ] NHibernate
- [ ] RepoDB
- [ ] ServiceStack
- [x] Documentation  
- [ ] LLBLGen Pro

**Comment by Grauenwolf** [comment]
Remaining ORM tickets created.
