### ISSUE TITLE
Entity Framework

### ISSUE THREAD

**Issue by Grauenwolf** [Grauenwolf/DotNet-ORM-Cookbook#34]
Entity Framework Core has some serious limitations compared to Entity Framework 6.x, so people have been asking that both are included.

We'll have to do some research to determine the actual differences so that appropriate use cases can be created.

**Comment by Grauenwolf** [comment]
Open question: how should the entities be created? Are EDMX files still the right way to go for EF 6.x? Or is code-first preferable?

**Comment by FransBouma** [comment]
code first is preferable, see limitations: https://www.llblgen.com/Documentation/5.6/Entity%20Framework/V56/PresetsAvailable.htm#limitations-of-entity-framework-v6-on-.net-standard-2.1

**Comment by Grauenwolf** [comment]
Ref: https://docs.microsoft.com/en-us/ef/ef6/modeling/code-first/workflows/existing-database?redirectedfrom=MSDN#3-reverse-engineer-model

**Comment by Grauenwolf** [comment]
EDMX offers better support for stored procs than Code First. But EDMX is basically dead so I don't think it would be appropriate to include it here.

I do have to say this is annoying though. I don't understand why they decided to expose things through EDMX that you can't do via code-first. If anything I would have figured it to be the other way around.

**Comment by FransBouma** [comment]
EDMX isn't really dead tho. EF 6.3+ runs on .NET Core with EDMX. I don't think a lot of new projects will use it tho, but a lot of stuff is still using it and likely will now migrate to .net core using ef 6.3+

**Comment by Grauenwolf** [comment]
Ugh, that just makes the question harder. 

I don't want to show two complete sets of examples, Code First and EDMX, but there are differences.

**Comment by FransBouma** [comment]
Perhaps the EF team can help themselves :) You could open an issue on the ef repo pointing to this repo and asking them whether they want to contribute, it's in their best interest after all :)

**Comment by FransBouma** [comment]
I could generate an EDMX using project from the llblgenproj project, if there's necessity for it. It will lack the EF designer goo so you can't design it in the EF designer (which would mean I'd have to take care of it, not something I'm looking particularly forward to :P ). I'm mentioning it here if it's required to have an EDMX project and it would otherwise take a lot of work (as it's 5 minutes for me)

**Comment by Grauenwolf** [comment]
I'm going to leave it off for now. We can revisit the question if people start asking us for EDMX.
