### ISSUE TITLE
Use Case: Transaction Commit/Rollback

### ISSUE THREAD

**Issue by mikependon** [Grauenwolf/DotNet-ORM-Cookbook#35]
An ORM should show how to to transaction in a committed state.

- [x] Test cases
- [x] ADO
- [x] Chain
- [x] Dapper
- [x] EF Core
- [x] NHibernate
- [ ] RepoDB
- [ ] ServiceStack
- [x] Documentation  
- [x] LLBLGen Pro
- [x] LinqToDB

**Comment by Grauenwolf** [comment]
Should demonstrate a rollback as well.

**Comment by mikependon** [comment]
I opened #36 for that.

**Comment by Grauenwolf** [comment]
While I don't like the pattern, at some point we're going to have to demonstrate multiple repositories sharing one transaction.

**Comment by bbzippo** [comment]
Speaking of Transactions, in "Model with Children CRUD", only the Chain example inserts children in a single transaction. Would be nice if the other examples did that too.

**Comment by Grauenwolf** [comment]
Yea, we probably should do that for any that perform multiple actions in one logical operation.

**Comment by Grauenwolf** [comment]
@bbzippo, I've updated the ADO, Dapper, and EF Core examples as you requested. We've got open tickets for LLBL Gen Pro and RepoDb.

**Comment by Grauenwolf** [comment]
@FransBouma I already implemented this one for LLBLGen Pro.

**Comment by FransBouma** [comment]
Thanks! :D
