### ISSUE TITLE
Use Case: Transaction Rollback

### ISSUE THREAD

**Issue by mikependon** [Grauenwolf/DotNet-ORM-Cookbook#36]
An ORM should show how to to transaction in a rolled-back state.

This should be validated after the operation.

- [ ] Test cases
- [ ] ADO
- [ ] Chain
- [ ] Dapper
- [ ] EF Core
- [ ] NHibernate
- [ ] RepoDB
- [ ] ServiceStack
- [ ] Documentation  
- [ ] LLBL Gen Pro

**Comment by Grauenwolf** [comment]
I'm inclined to put the Commit and Rollback into the same use case. But we can talk about it more later.

**Comment by Grauenwolf** [comment]
Duplicate of #35
