### ISSUE TITLE
Use Case: Use a Non-Integrated Security Connection String (PSI = False)

### ISSUE THREAD

**Issue by mikependon** [Grauenwolf/DotNet-ORM-Cookbook#39]
This is important in a way that opening a connection would fail the ORM in the second next calls due to a default behavior of ADO.NET (removing the password).

- [ ] Test cases
- [ ] ADO
- [ ] Chain
- [ ] Dapper
- [ ] EF Core
- [ ] NHibernate
- [ ] RepoDB
- [ ] ServiceStack
- [ ] Documentation

**Comment by mikependon** [comment]
@Grauenwolf - this could be an invalid case, I just realized. But can we keep this one for now, I will try to analyze further.

As I said, we can put all scenarios here, but we need to limit the scope of this.

**Comment by Grauenwolf** [comment]
Yea, I was wondering where you were going with this one. But I figure we can just add all of our ideas now and then pick the good ones later.

**Comment by mikependon** [comment]
Well, I have a changes on the core implementation of RepoDb with this.

With this stack calls.

1. User call the *connection.ExecuteQuery<Customer>(sql, param)*.
2. RepoDb is calling the *DbFieldCache.Get<Customer>()* - pre-cache the *Customer* scheme definitions.
3. RepoDb is failing at *DbCommand.ExecuteReader()*, due to an already opened-connection state.

I have fixed that one already.

However, I would assume how is the other ORM handles that?

**Comment by Grauenwolf** [comment]
I see what you're saying. 

That's really only a potential problem for databases that read schema at runtime. More of an edge case for you and I to deal with than something that the cookbook needs.

In Chain you first create a global DataSource for each connection string. Then you would use this syntax:

    var openDS = BaseDataSource.CreateOpenDataSource(myConnection, myTransaction);

The new DataSource uses the BaseDataSource to lookup schema. So I don't have to deal with connection string issues at all.

**Comment by mikependon** [comment]
That is because you persists the ConnectionString as a property of your BaseDataSource. Right?

**Comment by Grauenwolf** [comment]
Yes.

**Comment by mikependon** [comment]
Great and cheers! In *RepoDb*, that's the thing that I have avoided to implement *DbContext*.

**Comment by Grauenwolf** [comment]
RepoDb specific. Closing for now.

**Comment by mikependon** [comment]
This is not RepoDb specific. In your case, do you have scenarios which you query the DB multiple times within your DataSources? In that case, you will fail.
