### ISSUE TITLE
Replace the word "Repository" with the word "Scenario" in class names

### ISSUE THREAD

**Issue by Grauenwolf** [Grauenwolf/DotNet-ORM-Cookbook#42]
The term 'repository' makes people cranky because of the varying definitions and expectations around that name.

So instead of `SingleModelCrudAsyncRepository` we should use a name with fewer connotations such as `SingleModelCrudAsyncDAL`.

**Comment by Grauenwolf** [comment]
I decided against this. The term DAL refers to the whole layer, not just one class.

Instead I added an FAQ to explain how we're using the term.

**Comment by Grauenwolf** [comment]
https://github.com/Grauenwolf/DotNet-ORM-REf: Cookbook/commit/afaf784ebd36e93dfe9c923de03f4afbf8893a82

**Comment by Grauenwolf** [comment]
Still not a perfect name, but I think `ModelWithChildrenScenario` is a better pattern than `ModelWithChildrenRepository` for the class names. 

What do you all think?

@mikependon @mattjcowan @FransBouma

**Comment by Grauenwolf** [comment]
We could also use `ModelWithChildrenUseCase`. I just don't want "repository" in the name if we can avoid it.

**Comment by FransBouma** [comment]
UseCase or Scenario are indeed both better, I don't have a preference for either of the two, both are ok by me :)

**Comment by mikependon** [comment]
IMO, any access layer must be suffixes with 'DAL' or 'Repository'. That's how we also do as a standard, also, the ORM libraries usually reside on that layer as well. Of course, I may think that I am out-of-data already :)

However, since this cookbook caters different scenario. Both are okay actually. But it should be a new layer? I think, there should be a layer of 'Scenarios' or 'UseCases' here.

> TestSuite - Scenarios - Repositories

Or

> ModelWithChildrenUseCaseTest - ModelWithChildrenUseCase - (CookbookDbRepository/EmployeeRepository/EmployeeClassificationRepository)

I am just concerning about the separation-of-concerns of that layer.

**Comment by Grauenwolf** [comment]
> But it should be a new layer?

I think we should leave it to individual ORMs to make that decision.

**Comment by FransBouma** [comment]
The tests are showing use cases, not 'a dal' so using it as a dal is IMHO not really correct. 'Repository' suggests indeed that one can use it as a repository which is indeed not what we should propagate. Perhaps 'Scenarios' is the best approach; joins -> here are some join scenarios and this is how each orm does that. No-one would have a 'JoinRepository' in their code (at least I hope they don't ;) )

**Comment by mikependon** [comment]
> I think we should leave it to individual ORMs to make that decision.

Yes, we can do this if this could be standardized here.

I am saying that 'Repository' is actually correct when touching the database (or maybe DAL as well). But, there should be a new layer in between 'TestSuite' and 'Repository', and I can think of that - it is the 'UseCase/Scenario'. The Class-Under-Tests are the 'UseCase/Scenario' classes.

**Comment by Grauenwolf** [comment]
Done.
