### ISSUE TITLE
RepoDB: Model with FK to lookup table use case

### ISSUE THREAD

**Issue by Grauenwolf** [Grauenwolf/DotNet-ORM-Cookbook#53]
See #14

**Comment by mikependon** [comment]
Just assign all the things-to-do to me for RepoDb, I will revisit them all soon. Thanks

**Comment by mikependon** [comment]
IMHO, the HR.EmployeeDetail view must not be present. I think, this scenario is a good candidate to showcase the capability of the ORM to handle the actual parent-child relationship without the help of the combined resultsets like HR.EmployeeDetail view is doing.

I would somehow say, this view should be removed and have the other cater the table-based direct queries.

Anyway, I have never used the HR.EmployeeDetail view in my repository. :)

**Comment by Grauenwolf** [comment]
You're not required to use it, but there's nothing wrong with taking advantage of views in the database.

**Comment by mikependon** [comment]
Was not it a different scenario when using it?

Why? By using this, we can just simply hack the *Employee* class to simplify the process of decomposition of *EmployeeClassification* within the memory (through property values assignment). We defeat the purpose of Object-Graph, 2 DB queries or JOIN feature.

**Comment by Grauenwolf** [comment]
We can have a separate use case demonstrating client-side joins. 

The point of this one is to demonstrate the correct way of handling the lookup table use case with a given ORM. Technically speaking, an ORM could do everything via stored procedures so long as it passes the tests.

**Comment by mikependon** [comment]
Okay. Fair enough. Then I will maybe re-issue a PR to this soon. Thanks

**Comment by Grauenwolf** [comment]
Added #86 for client side joins.
