### ISSUE TITLE
HR.EmployeeClassification.IsEmployee isn't nullable in the DDL SQL, yet is treated as such in the code

### ISSUE THREAD

**Issue by FransBouma** [Grauenwolf/DotNet-ORM-Cookbook#57]
It has a NOT NULL clause in the ddl sql yet the code in e.g. EF Core's code treats it like a nullable field.

**Comment by Grauenwolf** [comment]
This is generated by EF Core's scaffolding command when it detects a non-nullable field with a default value. 

I think ServiceStack was doing something weird here too. 

I am intending on adding some more use cases that focus just on the handling of default values.

**Comment by FransBouma** [comment]
Ah, all ok then :)
