### ISSUE TITLE
What's the purpose of the related EmployeeSpecification in ModelWithLookupComplexRepository.Create?

### ISSUE THREAD

**Issue by FransBouma** [Grauenwolf/DotNet-ORM-Cookbook#59]
This method is misleading, and a test, ModelWithLookupComplexTests.FoulLookupTable is wrong (as in: what is it testing? That the signature on the repository is wrong?)

The main issue is that the FoulLookup test creates an entity graph and persists this through the ModelWithLookupComplexRepository.Create(). However, as the method changes the entity, saving the graph thus will also save the related entity, so both the new Employee and the related EmployeeClassification entity are saved (as both are changed, employee is new and its associated EmployeeClassification has been changed (FoulLookup, line 179)

If the related entity EmployeeClassification shouldn't be persisted, then the repository should clearly tell me that. However as microORMs don't do graph persistence this isn't really visible, and the EF Core repository reads a new instance of the passed in EmployeeClassification entity (of course otherwise the test would fail, but this makes **no sense at all**. No-one in production would use it this way. )

I can of course tell my framework not to persist things recursively and the test will pass. That's not the point: this is a 'recipe' book for people who want to see how things are done. IMHO the whole point of the test and repository is wrong and doesn't teach anyone anything other than how not to do it.

**Comment by FransBouma** [comment]
Same thing with the update. I now have to block recursive graph updates *everywhere* because some microORM can't deal with this and the test explicitly pushes a change in a related entity to the repository. Sorry, what's the point of these repositories anyway if they can't deal with related entities :D yeah I know DDD the book blablabla, that's why some people write books and others write software.

**Comment by Grauenwolf** [comment]
This use case covers scenarios where you explicitly don't want recursive saves. For example, when the child object(s) represent lookup tables that the user doesn't have permission to edit.

I see this from time to time in "REST" frameworks where you always pass around objects instead of just keys.

****

There's going to be another use case where you explicitly do want recursive saves. So turning it off globally might not be your best option. 

I realize that this is a frustrating use case, but in a way that's the point. This is the kind of stuff developers fight with from time to time.

**Comment by FransBouma** [comment]
Ok makes sense. I've limited the persistence in these particular repositories to a single entity to make sure things work ok, although I do think the main problem is the whole repository concept which is always a problematic affair (what to do with related entities in that case is a debate that never ends :) ). 

I can set the related entity also to readonly in my model, but that's in this case not useful as the same entity is also used for updates :)

**Comment by FransBouma** [comment]
Can be closed. :)
