### ISSUE TITLE
Change RepoDB to use DbRepository or BaseRepository in the CRUD examples

### ISSUE THREAD

**Issue by mikependon** [Grauenwolf/DotNet-ORM-Cookbook#6]
First, I personally thanked you as always.

Your implementation is more generic and honestly we are also doing the same thing here in the organization (as always). Due to the fact of coding legacy when using *Dapper* :)

Anyway, there is a much more explicit implementation when targeting a *Data Entity* when creating a *Repository* object. I wish to use the *DbRepository* or *BaseRepository* instead as I am campaigning it to become more standard.

Here is the [wiki](https://github.com/mikependon/RepoDb/wiki/Implementing-a-Repository#inheritting-the-dbrepository).

Please advise and thank you in advance!

**Comment by Grauenwolf** [comment]
The goal here is to show the correct way of using a given ORM. So if you are telling me that BaseRepository is the correct way to use RepoDB, then that's what I want in the cookbook.

**Comment by Grauenwolf** [comment]
I've given you permissions to this repository. Feel free to make your changes and submit a pull request.

**Comment by Grauenwolf** [comment]
Done.
