### ISSUE TITLE
Implement the Try-Crud examples for RepoDB

### ISSUE THREAD

**Issue by Grauenwolf** [Grauenwolf/DotNet-ORM-Cookbook#7]
Wait until #6 is done, then use it as a template.

**Comment by mikependon** [comment]
FYI: Have this implemented on my own copy already. The changes were not yet tested.
Link: https://github.com/mikependon/DotNet-ORM-Cookbook/tree/master/ORM%20Cookbook/Recipes.RepoDb/TryCrud

**Comment by Grauenwolf** [comment]
Done.
