### ISSUE TITLE
Implement CRUD Operations on Model with Child Records for RepoDb

### ISSUE THREAD

**Issue by Grauenwolf** [Grauenwolf/DotNet-ORM-Cookbook#76]
See #17

**Comment by mikependon** [comment]
Will take this one later. Thanks! :)

**Comment by mikependon** [comment]
Are we referring to Employee => EmployeeClassification relationship here?

**Comment by Grauenwolf** [comment]
This one is ProductLine and Products. So when you save ProductLine, it saves all of the Products under it at the same time.

**Comment by mikependon** [comment]
There is a performance problem here as we do not have bootstrapper. RepoDb tried to compile everything AOT before execution. These compilations happen in advance and seems creating a bit overhead.

Succeeding calls seems to be fast right after.

**Comment by Grauenwolf** [comment]
I've already removed the sample benchmarks from the project. Designing good benchmarks is hard and I want to focus on the educational aspects. 

That said, each project has a "warmup" test that will be run before any real tests are executed. So you can use this to trigger AOT compilation where appropriate.

**Comment by Grauenwolf** [comment]
To put it another way, we can say "ORM x needs 3 database calls, but ORM y can do it in 2". We can't say "ORM x is 3.2 ms faster than ORM y".

**Comment by mikependon** [comment]
> I want to focus on the educational aspects.

Great! :)
