### ISSUE TITLE
Implement Views for LLBL Gen Pro

### ISSUE THREAD

**Issue by Grauenwolf** [Grauenwolf/DotNet-ORM-Cookbook#89]
See #18

**Comment by FransBouma** [comment]
Starting... (btw it's "LLBLGen Pro" :P No space between LLBL and Gen)

**Comment by Grauenwolf** [comment]
> Starting... (btw it's "LLBLGen Pro" :P No space between LLBL and Gen)

I've updated the label in GitHub. Looks like you already caught all instances of the mistake in the code.
