### ISSUE TITLE
Implment Joins use case for LLBL Gen Pro

### ISSUE THREAD

**Issue by Grauenwolf** [Grauenwolf/DotNet-ORM-Cookbook#96]
See #86

**Comment by FransBouma** [comment]
In the Joins methods there's a clause:
`IsEmployee = ec.IsEmployee ?? true,`
but that's always non-null, as the join is an inner join and the table field isn't nullable. Like in the EF entity:

```
        [Required]
        public bool? IsEmployee { get; set; }
```
a required nullable :D

I've removed these coalesce instructions from my tests.

**Comment by FransBouma** [comment]
Also (in the doc page)

> EF Core native supports joins, but not projections. Multiple objects need to be explicitly mapped.

This is a bit misleading. It does support projections, you just have to specify them, like with any projection code. Dapper (and my plain SQL api as well) gets away with it by reflecting over the properties, in good faith that the fields with the same names mean the same thing.

**Comment by FransBouma** [comment]
I've updated the doc page a bit that they don't support 'implicit' projections. 

I've added 2 versions of my repository, one with plain linq projections and one using design time projection definitions in the designer, which can be used in a linq query to easily project the set to a poco.

**Comment by Grauenwolf** [comment]
> I've updated the doc page a bit that they don't support 'implicit' projections.

Thank you.
