### ISSUE TITLE
Use Case: Upsert

### ISSUE THREAD

**Issue by Grauenwolf** [Grauenwolf/DotNet-ORM-Cookbook#99]
Perform an Insert-Or-Update operation.

TODO: 
* Add `DivisionCode char(3)` to HR.Division 
* ~~Make `DivisionName` unique~~ We can use another column such as MaxEmployees

Scenario 1: Client provides a `Division` object. If `DivisionKey` is 0, insert. Otherwise update.
Scenario 2: Client provides a `Division` object. If `DivisionName` doesn't exist in the database, insert. Otherwise update. `DivisionKey` will be 0 either way.

In both scenarios, return the actual `DivisionKey`.

**Comment by FransBouma** [comment]
Does this have to be done with a native upsert statement? (merge)? Otherwise it'll be a messy locking scenario (I don't support upserts for instance)

**Comment by Grauenwolf** [comment]
Any method so long as the goal is achived.

**Comment by Grauenwolf** [comment]
Remaining ORM tickets created.
